// List of Dutch cities for validation
export const DUTCH_CITIES = [
  "Amsterdam",
  "Rotterdam",
  "Den Haag",
  "Utrecht",
  "Eindhoven",
  "Groningen",
  "Tilburg",
  "Almere",
  "Breda",
  "Nijmegen",
  "Enschede",
  "Haarlem",
  "Arnhem",
  "Zaanstad",
  "Amersfoort",
  "Apeldoorn",
  "s-Hertogenbosch",
  "Hoofddorp",
  "Maastricht",
  "Leiden",
  "Dordrecht",
  "Zoetermeer",
  "Zwolle",
  "Deventer",
  "Delft",
  "Alkmaar",
  "Heerlen",
  "Venlo",
  "Leeuwarden",
  "Amsterdam-Zuidoost",
  "Hilversum",
  "Amstelveen",
  "Roosendaal",
  "Purmerend",
  "Oss",
  "Schiedam",
  "Spijkenisse",
  "Helmond",
  "Vlaardingen",
  "Almelo",
  "Nieuwegein",
  "Sittard",
  "Lelystad",
  "Hengelo",
  "Veenendaal",
  "Gouda",
  "Alphen aan den Rijn",
  "Katwijk",
  "Ede",
  "Waddinxveen",
] as const;

// Workshop pricing is now fully database-driven.
// See: Workshop + PriceTier models in prisma/schema.prisma
// Admin: /workshop-catalog in goeduitje-backend
