// List of Dutch cities for validation
export const DUTCH_CITIES = [
  "Amsterdam",
  "Rotterdam",
  "Den Haag",
  "Utrecht",
  "Eindhoven",
  "Groningen",
  "Tilburg",
  "Almere",
  "Breda",
  "Nijmegen",
  "Enschede",
  "Haarlem",
  "Arnhem",
  "Zaanstad",
  "Amersfoort",
  "Apeldoorn",
  "s-Hertogenbosch",
  "Hoofddorp",
  "Maastricht",
  "Leiden",
  "Dordrecht",
  "Zoetermeer",
  "Zwolle",
  "Deventer",
  "Delft",
  "Alkmaar",
  "Heerlen",
  "Venlo",
  "Leeuwarden",
  "Amsterdam-Zuidoost",
  "Hilversum",
  "Amstelveen",
  "Roosendaal",
  "Purmerend",
  "Oss",
  "Schiedam",
  "Spijkenisse",
  "Helmond",
  "Vlaardingen",
  "Almelo",
  "Nieuwegein",
  "Sittard",
  "Lelystad",
  "Hengelo",
  "Veenendaal",
  "Gouda",
  "Alphen aan den Rijn",
  "Katwijk",
  "Ede",
  "Waddinxveen",
] as const;

// Workshops configuration
export const WORKSHOPS = [
  {
    id: "kookworkshop",
    name: "Kookworkshop",
    minParticipants: 1,
    maxParticipants: null, // no max limit
  },
  {
    id: "stadsspel",
    name: "Stadsspel",
    minParticipants: 6,
    maxParticipants: null,
  },
  {
    id: "the-game",
    name: "The Game",
    minParticipants: 6,
    maxParticipants: null,
  },
  {
    id: "beachvolleybal",
    name: "Beachvolleybal",
    minParticipants: 6,
    maxParticipants: null,
  },
  {
    id: "koffie-thee",
    name: "Koffie & Thee",
    minParticipants: 6,
    maxParticipants: null,
  },
  {
    id: "design-tshirt",
    name: "Design Your T-shirt",
    minParticipants: 6,
    maxParticipants: null,
  },
] as const;

export type WorkshopId = (typeof WORKSHOPS)[number]["id"];
