import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Sample testimonials based on Goeduitje's kookworkshops
const sampleReviews = [
  {
    googleReviewId: "review-1-sarah-vdberg",
    authorName: "Sarah van der Berg",
    authorPhotoUrl: null,
    rating: 5,
    text: "Een geweldige ervaring! Het team van Goeduitje heeft ons bedrijfsuitje tot een onvergetelijke dag gemaakt. De combinatie van plezier en sociale impact is uniek. De statushouders die ons begeleidden waren zo enthousiast en lieten ons de lekkerste Arabische gerechten maken.",
    relativeTime: "2 weken geleden",
    reviewTime: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    language: "nl",
    sortOrder: "most_relevant",
    isVisible: true,
  },
  {
    googleReviewId: "review-2-mohammed-hassan",
    authorName: "Mohammed Al-Hassan",
    authorPhotoUrl: null,
    rating: 5,
    text: "De kookworkshop was fantastisch. Niet alleen hebben we als team beter leren samenwerken, maar we weten ook dat we tegelijkertijd iets goeds hebben gedaan voor mensen in nood. Heel mooi concept!",
    relativeTime: "3 weken geleden",
    reviewTime: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000),
    language: "nl",
    sortOrder: "most_relevant",
    isVisible: true,
  },
  {
    googleReviewId: "review-3-lisa-devries",
    authorName: "Lisa de Vries",
    authorPhotoUrl: null,
    rating: 5,
    text: "Onze collega's praten er nog steeds over! Een perfecte teambuilding activiteit met een sociale twist. De gerechten waren verrassend lekker en we hebben veel geleerd over de Arabische keuken.",
    relativeTime: "1 maand geleden",
    reviewTime: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    language: "nl",
    sortOrder: "most_relevant",
    isVisible: true,
  },
  {
    googleReviewId: "review-4-jasper-winters",
    authorName: "Jasper Winters",
    authorPhotoUrl: null,
    rating: 5,
    text: "Goeduitje denkt echt met je mee. Van begin tot eind was alles perfect geregeld. De sociale impact maakt het extra bijzonder. Ons hele team was enthousiast, zelfs de collega's die normaal niet van koken houden.",
    relativeTime: "1 maand geleden",
    reviewTime: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000),
    language: "nl",
    sortOrder: "most_relevant",
    isVisible: true,
  },
  {
    googleReviewId: "review-5-anna-jansen",
    authorName: "Anna Jansen",
    authorPhotoUrl: null,
    rating: 5,
    text: "We hebben met het team genoten van de Arabische kookworkshop. De koks waren zo gastvrij en deelden niet alleen recepten maar ook verhalen uit hun thuisland. Een bijzondere en leerzame ervaring!",
    relativeTime: "2 maanden geleden",
    reviewTime: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    language: "nl",
    sortOrder: "newest",
    isVisible: true,
  },
  {
    googleReviewId: "review-6-peter-bakker",
    authorName: "Peter Bakker",
    authorPhotoUrl: null,
    rating: 5,
    text: "Uitstekend georganiseerd bedrijfsuitje. De locatie was prachtig, de sfeer ontspannen en het eten heerlijk. Fijn om te zien hoe onze deelname bijdraagt aan de integratie van statushouders.",
    relativeTime: "2 maanden geleden",
    reviewTime: new Date(Date.now() - 65 * 24 * 60 * 60 * 1000),
    language: "nl",
    sortOrder: "newest",
    isVisible: true,
  },
  {
    googleReviewId: "review-7-emma-smit",
    authorName: "Emma Smit",
    authorPhotoUrl: null,
    rating: 4,
    text: "Leuke workshop! Het eten was heerlijk en de begeleiding was top. Enige minpuntje was dat we iets te weinig tijd hadden, maar voor de rest een aanrader.",
    relativeTime: "2 maanden geleden",
    reviewTime: new Date(Date.now() - 70 * 24 * 60 * 60 * 1000),
    language: "nl",
    sortOrder: "newest",
    isVisible: true,
  },
  {
    googleReviewId: "review-8-jan-kuiper",
    authorName: "Jan Kuiper",
    authorPhotoUrl: null,
    rating: 5,
    text: "Wat een feest! Als HR-manager zoek ik altijd naar teamactiviteiten met betekenis. Deze kookworkshop was precies dat: gezellig, leerzaam en maatschappelijk relevant. Volgend jaar weer!",
    relativeTime: "3 maanden geleden",
    reviewTime: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000),
    language: "nl",
    sortOrder: "most_relevant",
    isVisible: true,
  },
  {
    googleReviewId: "review-9-marieke-dejong",
    authorName: "Marieke de Jong",
    authorPhotoUrl: null,
    rating: 5,
    text: "De vegetarische workshop was een schot in de roos. Alle collega's, of ze nu vegetarier zijn of niet, waren onder de indruk van de smaken. De koks legden geduldig alles uit en deelden hun persoonlijke verhalen.",
    relativeTime: "3 maanden geleden",
    reviewTime: new Date(Date.now() - 95 * 24 * 60 * 60 * 1000),
    language: "nl",
    sortOrder: "newest",
    isVisible: true,
  },
  {
    googleReviewId: "review-10-thomas-vandam",
    authorName: "Thomas van Dam",
    authorPhotoUrl: null,
    rating: 5,
    text: "Professioneel, hartelijk en smaakvol. Goeduitje levert kwaliteit en doet dat met een goed hart. Onze klanten waren onder de indruk toen we hen meenamen naar deze workshop.",
    relativeTime: "4 maanden geleden",
    reviewTime: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000),
    language: "nl",
    sortOrder: "most_relevant",
    isVisible: true,
  },
];

// Sample recipes from cooking workshops - organized by course type
const sampleRecipes = [
  // VOORGERECHTEN
  {
    title: "Bruschetta met tomaat en basilicum",
    slug: "bruschetta-tomaat-basilicum",
    description:
      "Knapperig geroosterd brood met verse tomaten, basilicum en knoflook. Een klassiek Italiaans voorgerecht.",
    imageUrl:
      "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=800&h=600&fit=crop",
    prepTime: 10,
    cookTime: 5,
    servings: 4,
    difficulty: "Makkelijk",
    category: "Voorgerecht",
    ingredients: [
      "4 sneetjes ciabatta of stokbrood",
      "3 rijpe tomaten",
      "2 teentjes knoflook",
      "Verse basilicum",
      "Extra vierge olijfolie",
      "Zeezout en peper",
      "Balsamico azijn (optioneel)",
    ],
    steps: [
      "Snijd de tomaten in kleine blokjes en verwijder het zaad",
      "Meng de tomaten met fijngehakte basilicum, een scheutje olijfolie, zout en peper",
      "Rooster de broodsneden tot ze licht goudbruin zijn",
      "Wrijf de geroosterde sneden in met een gehalveerde knoflookteen",
      "Schep de tomatenmix op het brood",
      "Besprenkel met olijfolie en eventueel balsamico",
      "Serveer direct terwijl het brood nog warm is",
    ],
    tips: "Gebruik rijpe, smaakvolle tomaten voor het beste resultaat. Roma tomaten zijn ideaal omdat ze minder vocht bevatten.",
    isPublished: true,
  },
  {
    title: "Caprese salade",
    slug: "caprese-salade",
    description:
      "Frisse salade met mozzarella, tomaat en basilicum. Simpel maar heerlijk!",
    imageUrl:
      "https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=800&h=600&fit=crop",
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    difficulty: "Makkelijk",
    category: "Voorgerecht",
    ingredients: [
      "250g buffelmozzarella",
      "4 grote tomaten",
      "Verse basilicum",
      "Extra vierge olijfolie",
      "Balsamico glazuur",
      "Zeezout en versgemalen peper",
    ],
    steps: [
      "Snijd tomaten en mozzarella in plakken van ca. 1 cm dik",
      "Schik de plakken afwisselend op een bord",
      "Steek basilicumblaadjes tussen de plakken",
      "Besprenkel met olijfolie en balsamico",
      "Bestrooi met zeezout en peper",
      "Laat 10 minuten op kamertemperatuur staan voor optimale smaak",
    ],
    tips: "Gebruik mozzarella di bufala voor de beste smaak. Laat de ingrediënten op kamertemperatuur komen voordat je serveert.",
    isPublished: true,
  },
  {
    title: "Geitenkaas met honing en walnoten",
    slug: "geitenkaas-honing-walnoten",
    description:
      "Warme geitenkaas met honing, walnoten en veldsla. Perfect als voorgerecht.",
    imageUrl:
      "https://images.unsplash.com/photo-1559561853-08451507cbe7?w=800&h=600&fit=crop",
    prepTime: 10,
    cookTime: 10,
    servings: 4,
    difficulty: "Makkelijk",
    category: "Voorgerecht",
    ingredients: [
      "4 kleine geitenkaasjes (chèvre)",
      "100g walnoten",
      "3 eetlepels honing",
      "100g veldsla",
      "2 eetlepels olijfolie",
      "1 eetlepel balsamico azijn",
      "Versgemalen peper",
    ],
    steps: [
      "Verwarm de oven voor op 180°C",
      "Hak de walnoten grof",
      "Plaats de geitenkaasjes in een ovenschaal",
      "Besprenkel met honing en bestrooi met walnoten",
      "Bak 8-10 minuten in de oven tot de kaas zacht wordt",
      "Maak een dressing van olijfolie en balsamico",
      "Verdeel de veldsla over de borden en schep de dressing erover",
      "Plaats de warme geitenkaas op de sla",
      "Serveer direct",
    ],
    tips: "Je kunt de walnoten even roosteren voor extra smaak. Gebruik tijmhoning voor een aromatische twist.",
    isPublished: true,
  },

  // HOOFDGERECHTEN
  {
    title: "Spaghetti carbonara",
    slug: "spaghetti-carbonara",
    description:
      "Authentieke Italiaanse pasta carbonara met pancetta, ei en Parmezaanse kaas.",
    imageUrl:
      "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&h=600&fit=crop",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: "Gemiddeld",
    category: "Hoofdgerecht",
    ingredients: [
      "400g spaghetti",
      "200g pancetta of guanciale",
      "4 eierdooiers",
      "100g geraspte Parmezaanse kaas",
      "Versgemalen zwarte peper",
      "Zout",
    ],
    steps: [
      "Kook de spaghetti volgens de verpakking in ruim gezouten water",
      "Snijd de pancetta in blokjes en bak krokant in een grote pan",
      "Klop in een kom de eierdooiers met de Parmezaanse kaas en peper",
      "Schep een kopje pastakookwater opzij",
      "Giet de pasta af en doe terug in de pan (van het vuur)",
      "Voeg de pancetta toe aan de pasta",
      "Giet het eimengsel over de pasta en roer snel",
      "Voeg pastakookwater toe tot een romige saus ontstaat",
      "Serveer direct met extra Parmezaanse kaas en peper",
    ],
    tips: "De sleutel is om de pasta van het vuur te halen voordat je het ei toevoegt, anders krijg je roerei. De warmte van de pasta kookt het ei perfect.",
    isPublished: true,
  },
  {
    title: "Kip teriyaki met rijst",
    slug: "kip-teriyaki-rijst",
    description:
      "Sappige kip in zoete Japanse teriyaki saus. Serveer met gestoomde rijst en groenten.",
    imageUrl:
      "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800&h=600&fit=crop",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: "Gemiddeld",
    category: "Hoofdgerecht",
    ingredients: [
      "500g kipfilet",
      "300g jasmijnrijst",
      "4 eetlepels sojasaus",
      "3 eetlepels mirin",
      "2 eetlepels honing",
      "2 teentjes knoflook",
      "1 eetlepel verse gember",
      "1 eetlepel sesamolie",
      "Sesamzaad",
      "Lente-ui",
      "Broccoli voor erbij",
    ],
    steps: [
      "Kook de rijst volgens de verpakking",
      "Snijd de kip in blokjes van 2-3 cm",
      "Maak de teriyaki saus: meng sojasaus, mirin, honing, knoflook en gember",
      "Verhit sesamolie in een wok of grote pan",
      "Bak de kip 5-6 minuten tot goudbruin",
      "Giet de teriyaki saus over de kip",
      "Laat inkoken tot de saus dik en glanzend wordt",
      "Stoom ondertussen de broccoli",
      "Serveer de kip op de rijst met broccoli",
      "Garneer met sesamzaad en gesneden lente-ui",
    ],
    tips: "Voor extra smaak kun je de kip 30 minuten marineren in de helft van de teriyaki saus. Gebruik dan de andere helft om de kip mee te glazuren.",
    isPublished: true,
  },
  {
    title: "Pad Thai met garnalen",
    slug: "pad-thai-garnalen",
    description:
      "Thaise noedelschotel met garnalen, pinda's en limoen. Vol van smaak!",
    imageUrl:
      "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800&h=600&fit=crop",
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: "Gemiddeld",
    category: "Hoofdgerecht",
    ingredients: [
      "250g rijstnoedels",
      "300g grote garnalen",
      "2 eieren",
      "100g taugé",
      "3 lente-uitjes",
      "2 teentjes knoflook",
      "50g gezouten pinda's",
      "3 eetlepels vissaus",
      "2 eetlepels tamarindepasta",
      "2 eetlepels suiker",
      "1 limoen",
      "Koriander",
      "Chilipoeder",
      "Plantaardige olie",
    ],
    steps: [
      "Week de rijstnoedels in warm water volgens de verpakking",
      "Maak de saus: meng vissaus, tamarindepasta en suiker",
      "Verhit olie in een wok op hoog vuur",
      "Klop de eieren en bak ze als roerei, haal uit de wok",
      "Bak de garnalen 2-3 minuten, haal uit de wok",
      "Bak knoflook en gesneden lente-ui",
      "Voeg de uitgelekte noedels toe en roerbak 2 minuten",
      "Giet de saus erover en meng goed",
      "Voeg garnalen, ei en taugé toe",
      "Bak alles 2 minuten door elkaar",
      "Serveer met gehakte pinda's, koriander, limoenpartjes en chilipoeder",
    ],
    tips: "Het geheim van goede Pad Thai is het gebruik van hoog vuur en snel roerbakken. Zorg dat alle ingrediënten vooraf klaar staan.",
    isPublished: true,
  },

  // BIJGERECHTEN
  {
    title: "Geroosterde groenten uit de oven",
    slug: "geroosterde-groenten-oven",
    description:
      "Kleurrijke seizoensgroenten geroosterd met kruiden en olijfolie.",
    imageUrl:
      "https://images.unsplash.com/photo-1518779578993-ec3579fee39f?w=800&h=600&fit=crop",
    prepTime: 15,
    cookTime: 30,
    servings: 6,
    difficulty: "Makkelijk",
    category: "Bijgerecht",
    ingredients: [
      "2 paprika's (rood en geel)",
      "1 aubergine",
      "2 courgettes",
      "1 rode ui",
      "250g cherrytomaten",
      "4 teentjes knoflook",
      "4 eetlepels olijfolie",
      "Verse tijm en rozemarijn",
      "Zeezout en peper",
      "Balsamico azijn",
    ],
    steps: [
      "Verwarm de oven voor op 200°C",
      "Snijd alle groenten in gelijke stukken (ca. 3 cm)",
      "Meng de groenten in een grote kom met olijfolie, kruiden, zout en peper",
      "Verdeel de groenten over een met bakpapier beklede bakplaat",
      "Rooster 25-30 minuten, keer halverwege",
      "De groenten zijn klaar als ze zacht zijn en mooie bruine randjes hebben",
      "Besprenkel met balsamico voor het serveren",
    ],
    tips: "Snijd de groenten in gelijke stukken zodat ze tegelijk gaar zijn. Je kunt dit gerecht ook koud serveren als salade.",
    isPublished: true,
  },
  {
    title: "Griekse salade",
    slug: "griekse-salade",
    description:
      "Frisse salade met feta, olijven, tomaat en komkommer. Een mediterraan bijgerecht.",
    imageUrl:
      "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&h=600&fit=crop",
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: "Makkelijk",
    category: "Bijgerecht",
    ingredients: [
      "1 komkommer",
      "4 tomaten",
      "1 rode ui",
      "1 groene paprika",
      "200g feta kaas",
      "100g zwarte Kalamata olijven",
      "4 eetlepels olijfolie",
      "2 eetlepels rode wijnazijn",
      "1 theelepel gedroogde oregano",
      "Zout en peper",
    ],
    steps: [
      "Snijd de komkommer en tomaten in grove blokken",
      "Snijd de ui in halve ringen",
      "Snijd de paprika in repen",
      "Doe alle groenten in een saladekom",
      "Voeg de olijven toe",
      "Maak een dressing van olijfolie, azijn en oregano",
      "Giet de dressing over de salade en meng voorzichtig",
      "Verkruimel de feta erover",
      "Bestrooi met peper en eventueel extra oregano",
      "Laat 10 minuten marineren voor het serveren",
    ],
    tips: "Gebruik rijpe, smaakvolle tomaten en echte Griekse feta voor het beste resultaat. De salade is op z'n lekkerst op kamertemperatuur.",
    isPublished: true,
  },
  {
    title: "Zoete aardappel friet",
    slug: "zoete-aardappel-friet",
    description:
      "Gezonde frietjes van zoete aardappel uit de oven. Lekker knapperig!",
    imageUrl:
      "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=800&h=600&fit=crop",
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    difficulty: "Makkelijk",
    category: "Bijgerecht",
    ingredients: [
      "4 grote zoete aardappels",
      "3 eetlepels olijfolie",
      "1 theelepel paprikapoeder",
      "1 theelepel knoflookpoeder",
      "1/2 theelepel cayennepeper (optioneel)",
      "Zeezout en peper",
      "Verse rozemarijn (optioneel)",
    ],
    steps: [
      "Verwarm de oven voor op 220°C",
      "Schil de zoete aardappels (of laat de schil erop)",
      "Snijd in frieten van ca. 1 cm dik",
      "Spoel de frieten af met koud water en dep goed droog",
      "Meng met olijfolie en kruiden in een grote kom",
      "Verdeel de frieten in één laag over een bakplaat",
      "Bak 25-30 minuten, keer halverwege",
      "De frieten zijn klaar als ze goudbruin en krokant zijn",
      "Bestrooi met zeezout en serveer direct",
    ],
    tips: "Het geheim van krokante friet is ze goed drogen en in één laag bakken. Zorg dat de frieten elkaar niet raken op de bakplaat.",
    isPublished: true,
  },

  // More voorgerechten
  {
    title: "Tomatensoep met basilicum",
    slug: "tomatensoep-basilicum",
    description:
      "Romige tomatensoep met verse basilicum. Perfect als voorgerecht.",
    imageUrl:
      "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=600&fit=crop",
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: "Makkelijk",
    category: "Voorgerecht",
    ingredients: [
      "1kg rijpe tomaten",
      "1 ui",
      "2 teentjes knoflook",
      "500ml groentebouillon",
      "100ml slagroom",
      "Verse basilicum",
      "Olijfolie",
      "Zout en peper",
    ],
    steps: [
      "Snijd tomaten in kwarten, ui in ringen",
      "Bak ui en knoflook glazig in olijfolie",
      "Voeg tomaten toe en bak 5 minuten mee",
      "Giet bouillon erbij en laat 15 minuten koken",
      "Pureer de soep glad met een staafmixer",
      "Voeg slagroom toe en verwarm door",
      "Breng op smaak met zout en peper",
      "Garneer met verse basilicum",
    ],
    tips: "Voor extra smaak kun je de tomaten eerst roosteren in de oven. Serveer met krokant stokbrood.",
    isPublished: true,
  },
  {
    title: "Caesarsalade",
    slug: "caesarsalade",
    description:
      "Klassieke Caesarsalade met krokante croutons en Parmezaanse kaas.",
    imageUrl:
      "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&h=600&fit=crop",
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: "Makkelijk",
    category: "Voorgerecht",
    ingredients: [
      "2 romaine slakoppen",
      "100g Parmezaanse kaas",
      "4 sneetjes witbrood",
      "2 teentjes knoflook",
      "4 ansjovisfilets",
      "1 eierdooier",
      "2 eetlepels Dijon mosterd",
      "Sap van 1 citroen",
      "150ml olijfolie",
      "Worcestershiresaus",
      "Zout en peper",
    ],
    steps: [
      "Maak croutons: snijd brood in blokjes en bak goudbruin",
      "Was en droog de sla, scheur in grote stukken",
      "Maak de dressing: pureer ansjovis, knoflook, eierdooier, mosterd en citroensap",
      "Voeg langzaam olijfolie toe terwijl je blijft mixen",
      "Breng op smaak met Worcestershiresaus, zout en peper",
      "Meng de sla met de dressing",
      "Schep op borden en garneer met croutons en geschaafde Parmezaanse kaas",
    ],
    tips: "Voor een veiligere versie kun je gekookte eierdooier gebruiken of mayonaise als basis voor de dressing.",
    isPublished: true,
  },

  // More hoofdgerechten
  {
    title: "Lasagne bolognese",
    slug: "lasagne-bolognese",
    description:
      "Klassieke Italiaanse lasagne met rijke vleessaus en bechamelsaus.",
    imageUrl:
      "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800&h=600&fit=crop",
    prepTime: 30,
    cookTime: 60,
    servings: 6,
    difficulty: "Gemiddeld",
    category: "Hoofdgerecht",
    ingredients: [
      "500g gehakt",
      "1 ui",
      "2 teentjes knoflook",
      "800g tomatenblokjes",
      "2 eetlepels tomatenpuree",
      "250g lasagnebladen",
      "50g boter",
      "50g bloem",
      "500ml melk",
      "100g geraspte kaas",
      "Verse basilicum",
      "Olijfolie",
      "Zout en peper",
    ],
    steps: [
      "Maak de bolognesesaus: bak ui en knoflook, voeg gehakt toe",
      "Voeg tomaten en tomatenpuree toe, laat 20 minuten sudderen",
      "Maak bechamelsaus: smelt boter, voeg bloem toe, roer melk erdoor",
      "Verwarm de oven voor op 180°C",
      "Bouw de lasagne: laag saus, laag pasta, laag bechamel",
      "Herhaal tot de schaal vol is",
      "Eindig met bechamel en strooi kaas erover",
      "Bak 45 minuten in de oven tot goudbruin",
    ],
    tips: "Maak de saus een dag van tevoren voor nog betere smaak. Laat de lasagne 10 minuten rusten voor je aansnijdt.",
    isPublished: true,
  },
  {
    title: "Thaise rode curry met kip",
    slug: "thaise-rode-curry-kip",
    description:
      "Romige Thaise curry met kip en groenten. Lekker pittig en aromatisch!",
    imageUrl:
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&h=600&fit=crop",
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: "Gemiddeld",
    category: "Hoofdgerecht",
    ingredients: [
      "500g kipfilet",
      "400ml kokosmelk",
      "3 eetlepels rode currypasta",
      "1 rode paprika",
      "1 ui",
      "200g champignons",
      "2 eetlepels vissaus",
      "1 eetlepel suiker",
      "Verse basilicum",
      "Limoen",
      "Jasmijnrijst",
    ],
    steps: [
      "Snijd de kip in blokjes",
      "Bak de currypasta 1 minuut in een wok",
      "Voeg de helft van de kokosmelk toe en roer door",
      "Voeg de kip toe en bak 5 minuten",
      "Voeg groenten en de rest van de kokosmelk toe",
      "Voeg vissaus en suiker toe",
      "Laat 10 minuten sudderen",
      "Serveer met rijst, basilicum en limoen",
    ],
    tips: "Pas de hoeveelheid currypasta aan naar je pittigheidsvoorkeur. Voeg courgette of aubergine toe voor variatie.",
    isPublished: true,
  },
  {
    title: "Quiche lorraine",
    slug: "quiche-lorraine",
    description:
      "Franse hartige taart met spek, ei en room. Perfect voor lunch of diner.",
    imageUrl:
      "https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=800&h=600&fit=crop",
    prepTime: 20,
    cookTime: 45,
    servings: 6,
    difficulty: "Gemiddeld",
    category: "Hoofdgerecht",
    ingredients: [
      "1 rol bladerdeeg",
      "200g spekblokjes",
      "1 ui",
      "4 eieren",
      "200ml slagroom",
      "100ml melk",
      "100g geraspte Gruyère kaas",
      "Nootmuskaat",
      "Zout en peper",
    ],
    steps: [
      "Verwarm de oven voor op 180°C",
      "Bekleed een taartvorm met bladerdeeg",
      "Bak de spekblokjes krokant en bak de ui mee",
      "Verdeel spek en ui over de bodem",
      "Klop eieren met room, melk, kaas en kruiden",
      "Giet het eimengsel over het spek",
      "Bak 35-40 minuten tot de vulling gestold is",
      "Laat 10 minuten afkoelen voor je snijdt",
    ],
    tips: "Prik de bodem van het deeg in met een vork om luchtbellen te voorkomen. Serveer met een groene salade.",
    isPublished: true,
  },

  // More bijgerechten
  {
    title: "Aardappelgratin",
    slug: "aardappelgratin",
    description:
      "Romige aardappelschijfjes uit de oven met kaas. Een heerlijk bijgerecht!",
    imageUrl:
      "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&h=600&fit=crop",
    prepTime: 20,
    cookTime: 60,
    servings: 6,
    difficulty: "Makkelijk",
    category: "Bijgerecht",
    ingredients: [
      "1kg vastkokende aardappels",
      "300ml slagroom",
      "200ml melk",
      "2 teentjes knoflook",
      "100g geraspte Gruyère kaas",
      "Nootmuskaat",
      "Boter",
      "Zout en peper",
    ],
    steps: [
      "Verwarm de oven voor op 180°C",
      "Schil en snijd aardappels in dunne plakjes",
      "Verwarm room, melk, knoflook en kruiden",
      "Vet een ovenschaal in met boter",
      "Leg laagjes aardappel in de schaal",
      "Giet het roommengsel erover",
      "Strooi kaas erover",
      "Bak 60 minuten tot goudbruin en zacht",
    ],
    tips: "Snijd de aardappels zo dun mogelijk voor het beste resultaat. Gebruik een mandoline als je die hebt.",
    isPublished: true,
  },
  {
    title: "Coleslaw",
    slug: "coleslaw",
    description:
      "Knapperige koolsalade met romige dressing. Perfect bij barbecue!",
    imageUrl:
      "https://images.unsplash.com/photo-1625938145744-e380f1b5f0b7?w=800&h=600&fit=crop",
    prepTime: 15,
    cookTime: 0,
    servings: 6,
    difficulty: "Makkelijk",
    category: "Bijgerecht",
    ingredients: [
      "1/2 witte kool",
      "2 wortels",
      "1/2 rode ui",
      "150g mayonaise",
      "2 eetlepels azijn",
      "1 eetlepel suiker",
      "1 theelepel mosterd",
      "Zout en peper",
    ],
    steps: [
      "Snijd de kool heel fijn",
      "Rasp de wortels grof",
      "Snijd de ui in dunne ringen",
      "Maak de dressing: meng mayo, azijn, suiker en mosterd",
      "Breng op smaak met zout en peper",
      "Meng de groenten met de dressing",
      "Laat minimaal 30 minuten intrekken in de koelkast",
    ],
    tips: "De coleslaw wordt lekkerder als je hem een paar uur laat staan. Perfect om een dag van tevoren te maken.",
    isPublished: true,
  },
  {
    title: "Ratatouille",
    slug: "ratatouille",
    description: "Franse groentestoofpot met aubergine, courgette en tomaat.",
    imageUrl:
      "https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c?w=800&h=600&fit=crop",
    prepTime: 20,
    cookTime: 40,
    servings: 4,
    difficulty: "Makkelijk",
    category: "Bijgerecht",
    ingredients: [
      "1 aubergine",
      "2 courgettes",
      "2 paprika's",
      "4 tomaten",
      "1 ui",
      "3 teentjes knoflook",
      "Verse tijm en rozemarijn",
      "Olijfolie",
      "Zout en peper",
    ],
    steps: [
      "Snijd alle groenten in blokjes van 2 cm",
      "Bak de ui en knoflook glazig",
      "Voeg aubergine toe en bak 5 minuten",
      "Voeg courgette en paprika toe, bak 5 minuten",
      "Voeg tomaten en kruiden toe",
      "Laat 25 minuten zachtjes sudderen",
      "Breng op smaak met zout en peper",
      "Serveer warm of op kamertemperatuur",
    ],
    tips: "Ratatouille is ook heerlijk koud de volgende dag. Perfect bij vlees, vis of als vegetarisch hoofdgerecht.",
    isPublished: true,
  },

  // DESSERTS
  {
    title: "Tiramisu",
    slug: "tiramisu",
    description:
      "Klassiek Italiaans dessert met mascarpone, espresso en cacao. Hemels!",
    imageUrl:
      "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&h=600&fit=crop",
    prepTime: 30,
    cookTime: 0,
    servings: 8,
    difficulty: "Gemiddeld",
    category: "Dessert",
    ingredients: [
      "500g mascarpone",
      "4 eieren (gescheiden)",
      "100g suiker",
      "300ml sterke espresso (afgekoeld)",
      "3 eetlepels Amaretto of Marsala",
      "200g lange vingers",
      "Cacaopoeder voor bestroving",
      "Snufje zout",
    ],
    steps: [
      "Klop de eierdooiers met suiker tot ze licht en romig zijn",
      "Roer de mascarpone erdoor tot een glad mengsel",
      "Klop de eiwitten met een snufje zout stijf",
      "Spatel de eiwitten voorzichtig door het mascarponemengsel",
      "Meng de espresso met Amaretto in een bord",
      "Doop de lange vingers kort in de koffie",
      "Leg een laag gedoopte vingers in de bodem van een schaal",
      "Verdeel de helft van het mascarponemengsel erover",
      "Herhaal met nog een laag vingers en mascarpone",
      "Dek af en zet minimaal 4 uur (liefst een nacht) in de koelkast",
      "Bestrooi vlak voor serveren royaal met cacaopoeder",
    ],
    tips: "Doop de lange vingers snel in de koffie - als ze te lang weken worden ze papperig. Tiramisu is het lekkerst als je het een dag van tevoren maakt.",
    isPublished: true,
  },
  {
    title: "Brownies met walnoten",
    slug: "brownies-walnoten",
    description:
      "Rijke chocolade brownies met walnoten. Fudgy van binnen, krokant van buiten.",
    imageUrl:
      "https://images.unsplash.com/photo-1607920591413-4ec007e70023?w=800&h=600&fit=crop",
    prepTime: 15,
    cookTime: 25,
    servings: 12,
    difficulty: "Makkelijk",
    category: "Dessert",
    ingredients: [
      "200g pure chocolade",
      "175g ongezouten boter",
      "3 eieren",
      "250g suiker",
      "100g bloem",
      "30g cacaopoeder",
      "Snufje zout",
      "100g walnoten (grof gehakt)",
      "1 theelepel vanille-extract",
    ],
    steps: [
      "Verwarm de oven voor op 180°C",
      "Vet een vierkante bakblik in (20x20 cm) en bekleed met bakpapier",
      "Smelt chocolade en boter au bain marie",
      "Laat iets afkoelen",
      "Klop de eieren met suiker luchtig (5 minuten)",
      "Roer het chocolademengsel en vanille erdoor",
      "Zeef bloem, cacao en zout erboven en spatel voorzichtig door",
      "Voeg de walnoten toe",
      "Schep het beslag in de vorm",
      "Bak 22-25 minuten - de bovenkant moet glanzend zijn en licht kraken",
      "Laat volledig afkoelen voor je snijdt",
      "Snijd in 12 vierkanten",
    ],
    tips: "Bak niet te lang - brownies moeten fudgy zijn van binnen. Een prikker moet er met wat natte kruimels uitkomen, niet schoon.",
    isPublished: true,
  },
  {
    title: "Appeltaart met kaneel",
    slug: "appeltaart-kaneel",
    description:
      "Klassieke Nederlandse appeltaart met kaneelroom. Een blijvertje!",
    imageUrl:
      "https://images.unsplash.com/photo-1535920527002-b35e96722eb9?w=800&h=600&fit=crop",
    prepTime: 30,
    cookTime: 60,
    servings: 10,
    difficulty: "Gemiddeld",
    category: "Dessert",
    ingredients: [
      "300g bloem",
      "200g koude boter",
      "100g suiker",
      "1 ei",
      "Snufje zout",
      "1,5 kg zure appels",
      "100g rozijnen",
      "100g suiker",
      "2 theelepels kaneel",
      "30g paneermeel",
      "Sap van 1/2 citroen",
      "1 eierdooier voor bestrijken",
    ],
    steps: [
      "Maak het deeg: meng bloem, suiker en zout",
      "Voeg koude boter in blokjes toe en wrijf tot een kruimelig mengsel",
      "Voeg het ei toe en kneed tot een bal",
      "Wikkel in folie en leg 30 minuten in de koelkast",
      "Schil en snijd de appels in stukjes",
      "Meng appels met rozijnen, suiker, kaneel en citroensap",
      "Verwarm de oven voor op 180°C",
      "Rol 2/3 van het deeg uit en bekleed een springvorm",
      "Strooi paneermeel over de bodem",
      "Schep de appelvulling erin",
      "Rol de rest van het deeg uit en snijd repen voor het deksel",
      "Maak een ruitpatroon op de taart",
      "Bestrijk met losgeklopte eierdooier",
      "Bak 60 minuten tot goudbruin",
      "Laat afkoelen en serveer lauw met slagroom",
    ],
    tips: "Gebruik zure appels zoals Elstar of Goudrenet voor de beste smaak. Het paneermeel absorbeert vocht en voorkomt een natte bodem.",
    isPublished: true,
  },
  {
    title: "Cheesecake met fruit",
    slug: "cheesecake-fruit",
    description:
      "Romige Amerikaanse cheesecake met vers fruit. Een echte showstopper!",
    imageUrl:
      "https://images.unsplash.com/photo-1533134486753-c833f0ed4866?w=800&h=600&fit=crop",
    prepTime: 30,
    cookTime: 60,
    servings: 10,
    difficulty: "Gemiddeld",
    category: "Dessert",
    ingredients: [
      "200g digestive koekjes",
      "100g boter",
      "600g roomkaas",
      "200g suiker",
      "3 eieren",
      "200ml slagroom",
      "1 citroen (sap en rasp)",
      "1 theelepel vanille-extract",
      "Vers fruit voor topping",
    ],
    steps: [
      "Verwarm de oven voor op 160°C",
      "Verkruimel de koekjes en meng met gesmolten boter",
      "Druk het mengsel in een springvorm als bodem",
      "Klop roomkaas met suiker glad",
      "Voeg eieren één voor één toe",
      "Voeg room, citroensap en vanille toe",
      "Giet over de bodem en bak 50-60 minuten",
      "Laat volledig afkoelen in de oven",
      "Zet minimaal 4 uur in de koelkast",
      "Garneer met vers fruit voor serveren",
    ],
    tips: "Laat alle ingrediënten op kamertemperatuur komen voor een gladde vulling. Een waterbad in de oven voorkomt barsten.",
    isPublished: true,
  },
  {
    title: "Crème caramel",
    slug: "creme-caramel",
    description:
      "Frans dessert met zachte vanillecustard en karamelsaus. Elegant en lekker!",
    imageUrl:
      "https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&h=600&fit=crop",
    prepTime: 20,
    cookTime: 45,
    servings: 6,
    difficulty: "Gemiddeld",
    category: "Dessert",
    ingredients: [
      "150g suiker voor karamel",
      "500ml melk",
      "1 vanillestokje",
      "4 eieren",
      "75g suiker",
    ],
    steps: [
      "Maak karamel: verhit 150g suiker tot goudbruin",
      "Verdeel de karamel over 6 vormpjes",
      "Verwarm melk met vanillemerg tot net onder het kookpunt",
      "Klop eieren met 75g suiker",
      "Giet de warme melk bij het eimengsel",
      "Zeef en verdeel over de vormpjes",
      "Plaats de vormpjes in een ovenschaal met water",
      "Bak 40 minuten op 150°C",
      "Laat afkoelen en zet in de koelkast",
      "Stort om op borden voor serveren",
    ],
    tips: "Zorg dat de karamel niet te donker wordt, anders wordt hij bitter. De custard is gaar als hij nog licht wiebelt.",
    isPublished: true,
  },
  {
    title: "Chocolademousse",
    slug: "chocolademousse",
    description: "Luchtige mousse van pure chocolade. Simpel maar o zo lekker!",
    imageUrl:
      "https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?w=800&h=600&fit=crop",
    prepTime: 20,
    cookTime: 5,
    servings: 6,
    difficulty: "Gemiddeld",
    category: "Dessert",
    ingredients: [
      "200g pure chocolade (70% cacao)",
      "4 eieren (gescheiden)",
      "40g suiker",
      "250ml slagroom",
      "Snufje zout",
      "Cacaopoeder voor bestroving",
      "Chocoladekrullen voor garnering",
    ],
    steps: [
      "Smelt de chocolade au bain marie en laat iets afkoelen",
      "Klop de eiwitten met een snufje zout stijf",
      "Voeg geleidelijk de suiker toe en blijf kloppen",
      "Roer de eierdooiers door de afgekoelde chocolade",
      "Klop de slagroom halfstijf",
      "Spatel 1/3 van de eiwitten door de chocolade om te versoepelen",
      "Spatel voorzichtig de rest van de eiwitten erdoor",
      "Spatel als laatste de slagroom erdoor",
      "Verdeel over 6 glaasjes of kommen",
      "Zet minimaal 3 uur in de koelkast",
      "Bestrooi voor serveren met cacao en garneer met chocoladekrullen",
    ],
    tips: "Gebruik goede kwaliteit chocolade voor de beste smaak. Spatel alles voorzichtig door zodat de mousse luchtig blijft.",
    isPublished: true,
  },
];

async function main() {
  console.log("Seeding database with sample reviews...");

  // Upsert each review
  for (const review of sampleReviews) {
    await prisma.googleReview.upsert({
      where: { googleReviewId: review.googleReviewId },
      update: {
        ...review,
        fetchedAt: new Date(),
        lastSeenAt: new Date(),
      },
      create: {
        ...review,
        fetchedAt: new Date(),
        lastSeenAt: new Date(),
      },
    });
    console.log(`  Added review from ${review.authorName}`);
  }

  // Create cache metadata
  await prisma.googleReviewsCache.upsert({
    where: { id: "singleton" },
    update: {
      placeName: "Goeduitje - Kookworkshops",
      averageRating: 4.9,
      totalReviewCount: sampleReviews.length,
      lastFetchedAt: new Date(),
      fetchErrorCount: 0,
      lastErrorMessage: null,
    },
    create: {
      id: "singleton",
      placeId: "manual-seed",
      placeName: "Goeduitje - Kookworkshops",
      averageRating: 4.9,
      totalReviewCount: sampleReviews.length,
      lastFetchedAt: new Date(),
      fetchErrorCount: 0,
    },
  });

  console.log(`\nSeeded ${sampleReviews.length} reviews successfully!`);
  console.log("Visit /jullie-ervaringen to see the reviews page.");

  // Seed recipes
  console.log("\nSeeding database with sample recipes...");

  // First, delete all existing recipes to ensure clean state
  const deletedRecipes = await prisma.recipe.deleteMany({});
  console.log(`  Deleted ${deletedRecipes.count} existing recipes`);

  // Then create the new recipes
  for (const recipe of sampleRecipes) {
    await prisma.recipe.create({
      data: recipe,
    });
    console.log(`  Added recipe: ${recipe.title}`);
  }

  console.log(`\nSeeded ${sampleRecipes.length} recipes successfully!`);
  console.log("Visit /recepten to see the recipes page.");
}

main()
  .catch((e) => {
    console.error("Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
